### ISSUE TITLE
Step File

### ISSUE THREAD

**Issue by quangphuc91** [uStepper/uStepper-RobotArm-Rev3#1]
Hi

Can you share me the step file of uStepper Robot , i need to modify hole dimension and some part to fix with my printer because some hole small after printed

My email : quangphuc91@gmail.com

thank you very much

Have a nice day

**Comment by ChrisPetit** [comment]
Can the Small Gears also be released with 4mm holes? If not can the Step files for those gears made available so I can change the Axis hole diameter myself?

Thanks

**Comment by uStepperOld** [comment]
Hi,

I dont have the design as a step file.

Best regards,
Mogens
