### ISSUE TITLE
Problem with slave communication

### ISSUE THREAD

**Issue by BeebBenjamin** [uStepper/uStepper-RobotArm-Rev3#3]
Hi,
I am using the example code here with usteppers on another hobby project of mine.  I have built the blue tooth module and protoshield as per the instructable.  However, there seems to be a problem with the way the software talks to the slaves.  Communication from slave 1 is fine, it occurs almost instantaneously.  However, then I try and run a stepper from the slave 2 slot, communication lags by minutes or even not at all.  Am I missing a trick with the firmware?  I have tested both slaves on slave 1 and slave 2 and both work on slave 1 and both misbehave on slave 2.  I have checked my soldering even redoing it, but the problem is still present.  From your fritzing diagram and the example code you have here I assumed that both Rx lines to the slaves are connected to pin 5 of the master?

Here is the test example I am using:

#include <uStepper.h>
#include <SoftwareSerial.h>
#define SLAVEOUT 2
#define MICROSTEP 16//microstep setting of uStepper
#define RES (200.0*MICROSTEP)/360.0//calculate step pr. degree
#define STEPPRMM 53.55//step pr. mm for the rail used in the demo
#define MMPRSTEP 1/STEPPRMM//mm pr. step
#define MMPRDEG MMPRSTEP*RES//mm pr. degree

SoftwareSerial mySerial(4, 5); // RX, TX

uStepper stepper;

char val;

void setup() {
  Serial.begin(9600);//Setup serial communication on TX/RX
  mySerial.begin(9600);
  stepper.setup(PID,SIXTEEN,10,5,2.0,2.0,0.6);//enable PID
  stepper.setCurrent(50.0);//use software current setting
  stepper.setMaxAcceleration(20000);
  stepper.setMaxVelocity(4000);
  stepper.hardStop(SOFT);
 
  pinMode(SLAVEOUT, OUTPUT);//Output on slaves
  pinMode(3, INPUT);//Input from slave 1
  pinMode(8, INPUT);//Input from slave 2
}

void master()//Code running on Master
{
   if(Serial.available() > 0)
  {
    val = Serial.read();
  }
  if( val == 'A' )
  {
    stepper.setup(PID,SIXTEEN,100000,50000,1.0,0.02,0.006,0);
    stepper.hardStop(SOFT);
  } 
  if( val == 'B')
  {
    stepper.setup(PID,SIXTEEN,100000,50000,1.0,0.02,0.006,0);
    stepper.runContinous(CCW);
  }
  if( val == 'C')
  {
    stepper.setup(PID,SIXTEEN,10,5,2.0,2.0,0.6);
    stepper.moveToAngle(10, SOFT);
    stepper.setup(PID,SIXTEEN,100000,50000,1.0,0.02,0.006,0);
  }
  if( val == 'D')
  {
   stepper.setup(PID,SIXTEEN,10,5,2.0,2.0,0.6);
   stepper.moveToAngle(360, HARD);
  }
  if( val == 'E')
  {
    mySerial.println('A');
  }
  if( val == 'S')
  {
    mySerial.println('B');
  }
}

void slave()//Slave function - the functionality is pretty much the same as in the Master, so look at the comments there for reference.
{
   if(Serial.available() > 0)
  {
    val = Serial.read();
  }
  if( val == 'A')
  {
    stepper.setup(PID,SIXTEEN,100000,50000,1.0,0.02,0.006,0);
    stepper.hardStop(SOFT);
  }
  if( val =='B')
  {
    stepper.setup(PID,SIXTEEN,100000,50000,1.0,0.02,0.006);
    stepper.runContinous(CCW);
  }
}

void loop() {//comment in the appropriate function

//master(); 
slave();
}

**Comment by uStepperOld** [comment]
Hi,
It sounds like a wiring problem more than a software related problem, since you, as many others, are using the example code we have provided. This code functions for us and many others. Could you send us an email with info on how you have wired them up - preferably with pictures on sales at ustepper.com ?
